# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huyongxi/worksp/catclient

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huyongxi/worksp/catclient

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huyongxi/worksp/catclient/CMakeFiles /home/huyongxi/worksp/catclient/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huyongxi/worksp/catclient/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named catclient

# Build rule for target.
catclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catclient
.PHONY : catclient

# fast build rule for target.
catclient/fast:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/build
.PHONY : catclient/fast

# target to build an object file
src/ccat/client.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client.o
.PHONY : src/ccat/client.o

# target to preprocess a source file
src/ccat/client.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client.i
.PHONY : src/ccat/client.i

# target to generate assembly for a file
src/ccat/client.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client.s
.PHONY : src/ccat/client.s

# target to build an object file
src/ccat/client_config.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client_config.o
.PHONY : src/ccat/client_config.o

# target to preprocess a source file
src/ccat/client_config.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client_config.i
.PHONY : src/ccat/client_config.i

# target to generate assembly for a file
src/ccat/client_config.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/client_config.s
.PHONY : src/ccat/client_config.s

# target to build an object file
src/ccat/context.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/context.o
.PHONY : src/ccat/context.o

# target to preprocess a source file
src/ccat/context.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/context.i
.PHONY : src/ccat/context.i

# target to generate assembly for a file
src/ccat/context.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/context.s
.PHONY : src/ccat/context.s

# target to build an object file
src/ccat/encoder.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder.o
.PHONY : src/ccat/encoder.o

# target to preprocess a source file
src/ccat/encoder.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder.i
.PHONY : src/ccat/encoder.i

# target to generate assembly for a file
src/ccat/encoder.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder.s
.PHONY : src/ccat/encoder.s

# target to build an object file
src/ccat/encoder_binary.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_binary.o
.PHONY : src/ccat/encoder_binary.o

# target to preprocess a source file
src/ccat/encoder_binary.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_binary.i
.PHONY : src/ccat/encoder_binary.i

# target to generate assembly for a file
src/ccat/encoder_binary.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_binary.s
.PHONY : src/ccat/encoder_binary.s

# target to build an object file
src/ccat/encoder_text.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_text.o
.PHONY : src/ccat/encoder_text.o

# target to preprocess a source file
src/ccat/encoder_text.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_text.i
.PHONY : src/ccat/encoder_text.i

# target to generate assembly for a file
src/ccat/encoder_text.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/encoder_text.s
.PHONY : src/ccat/encoder_text.s

# target to build an object file
src/ccat/functions.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/functions.o
.PHONY : src/ccat/functions.o

# target to preprocess a source file
src/ccat/functions.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/functions.i
.PHONY : src/ccat/functions.i

# target to generate assembly for a file
src/ccat/functions.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/functions.s
.PHONY : src/ccat/functions.s

# target to build an object file
src/ccat/message.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message.o
.PHONY : src/ccat/message.o

# target to preprocess a source file
src/ccat/message.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message.i
.PHONY : src/ccat/message.i

# target to generate assembly for a file
src/ccat/message.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message.s
.PHONY : src/ccat/message.s

# target to build an object file
src/ccat/message_aggregator.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator.o
.PHONY : src/ccat/message_aggregator.o

# target to preprocess a source file
src/ccat/message_aggregator.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator.i
.PHONY : src/ccat/message_aggregator.i

# target to generate assembly for a file
src/ccat/message_aggregator.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator.s
.PHONY : src/ccat/message_aggregator.s

# target to build an object file
src/ccat/message_aggregator_event.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_event.o
.PHONY : src/ccat/message_aggregator_event.o

# target to preprocess a source file
src/ccat/message_aggregator_event.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_event.i
.PHONY : src/ccat/message_aggregator_event.i

# target to generate assembly for a file
src/ccat/message_aggregator_event.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_event.s
.PHONY : src/ccat/message_aggregator_event.s

# target to build an object file
src/ccat/message_aggregator_metric.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_metric.o
.PHONY : src/ccat/message_aggregator_metric.o

# target to preprocess a source file
src/ccat/message_aggregator_metric.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_metric.i
.PHONY : src/ccat/message_aggregator_metric.i

# target to generate assembly for a file
src/ccat/message_aggregator_metric.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_metric.s
.PHONY : src/ccat/message_aggregator_metric.s

# target to build an object file
src/ccat/message_aggregator_trans.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_trans.o
.PHONY : src/ccat/message_aggregator_trans.o

# target to preprocess a source file
src/ccat/message_aggregator_trans.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_trans.i
.PHONY : src/ccat/message_aggregator_trans.i

# target to generate assembly for a file
src/ccat/message_aggregator_trans.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_aggregator_trans.s
.PHONY : src/ccat/message_aggregator_trans.s

# target to build an object file
src/ccat/message_helper.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_helper.o
.PHONY : src/ccat/message_helper.o

# target to preprocess a source file
src/ccat/message_helper.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_helper.i
.PHONY : src/ccat/message_helper.i

# target to generate assembly for a file
src/ccat/message_helper.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_helper.s
.PHONY : src/ccat/message_helper.s

# target to build an object file
src/ccat/message_id.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_id.o
.PHONY : src/ccat/message_id.o

# target to preprocess a source file
src/ccat/message_id.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_id.i
.PHONY : src/ccat/message_id.i

# target to generate assembly for a file
src/ccat/message_id.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_id.s
.PHONY : src/ccat/message_id.s

# target to build an object file
src/ccat/message_manager.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_manager.o
.PHONY : src/ccat/message_manager.o

# target to preprocess a source file
src/ccat/message_manager.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_manager.i
.PHONY : src/ccat/message_manager.i

# target to generate assembly for a file
src/ccat/message_manager.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_manager.s
.PHONY : src/ccat/message_manager.s

# target to build an object file
src/ccat/message_sender.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_sender.o
.PHONY : src/ccat/message_sender.o

# target to preprocess a source file
src/ccat/message_sender.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_sender.i
.PHONY : src/ccat/message_sender.i

# target to generate assembly for a file
src/ccat/message_sender.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_sender.s
.PHONY : src/ccat/message_sender.s

# target to build an object file
src/ccat/message_tree.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_tree.o
.PHONY : src/ccat/message_tree.o

# target to preprocess a source file
src/ccat/message_tree.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_tree.i
.PHONY : src/ccat/message_tree.i

# target to generate assembly for a file
src/ccat/message_tree.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/message_tree.s
.PHONY : src/ccat/message_tree.s

# target to build an object file
src/ccat/monitor.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor.o
.PHONY : src/ccat/monitor.o

# target to preprocess a source file
src/ccat/monitor.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor.i
.PHONY : src/ccat/monitor.i

# target to generate assembly for a file
src/ccat/monitor.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor.s
.PHONY : src/ccat/monitor.s

# target to build an object file
src/ccat/monitor_collector.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor_collector.o
.PHONY : src/ccat/monitor_collector.o

# target to preprocess a source file
src/ccat/monitor_collector.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor_collector.i
.PHONY : src/ccat/monitor_collector.i

# target to generate assembly for a file
src/ccat/monitor_collector.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/monitor_collector.s
.PHONY : src/ccat/monitor_collector.s

# target to build an object file
src/ccat/router_json_parser.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/router_json_parser.o
.PHONY : src/ccat/router_json_parser.o

# target to preprocess a source file
src/ccat/router_json_parser.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/router_json_parser.i
.PHONY : src/ccat/router_json_parser.i

# target to generate assembly for a file
src/ccat/router_json_parser.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/router_json_parser.s
.PHONY : src/ccat/router_json_parser.s

# target to build an object file
src/ccat/server_connection_manager.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/server_connection_manager.o
.PHONY : src/ccat/server_connection_manager.o

# target to preprocess a source file
src/ccat/server_connection_manager.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/server_connection_manager.i
.PHONY : src/ccat/server_connection_manager.i

# target to generate assembly for a file
src/ccat/server_connection_manager.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/server_connection_manager.s
.PHONY : src/ccat/server_connection_manager.s

# target to build an object file
src/ccat/transaction.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/transaction.o
.PHONY : src/ccat/transaction.o

# target to preprocess a source file
src/ccat/transaction.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/transaction.i
.PHONY : src/ccat/transaction.i

# target to generate assembly for a file
src/ccat/transaction.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/ccat/transaction.s
.PHONY : src/ccat/transaction.s

# target to build an object file
src/cppcat/client.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/client.o
.PHONY : src/cppcat/client.o

# target to preprocess a source file
src/cppcat/client.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/client.i
.PHONY : src/cppcat/client.i

# target to generate assembly for a file
src/cppcat/client.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/client.s
.PHONY : src/cppcat/client.s

# target to build an object file
src/cppcat/event.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/event.o
.PHONY : src/cppcat/event.o

# target to preprocess a source file
src/cppcat/event.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/event.i
.PHONY : src/cppcat/event.i

# target to generate assembly for a file
src/cppcat/event.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/event.s
.PHONY : src/cppcat/event.s

# target to build an object file
src/cppcat/metric.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/metric.o
.PHONY : src/cppcat/metric.o

# target to preprocess a source file
src/cppcat/metric.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/metric.i
.PHONY : src/cppcat/metric.i

# target to generate assembly for a file
src/cppcat/metric.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/metric.s
.PHONY : src/cppcat/metric.s

# target to build an object file
src/cppcat/transaction.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/transaction.o
.PHONY : src/cppcat/transaction.o

# target to preprocess a source file
src/cppcat/transaction.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/transaction.i
.PHONY : src/cppcat/transaction.i

# target to generate assembly for a file
src/cppcat/transaction.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/cppcat/transaction.s
.PHONY : src/cppcat/transaction.s

# target to build an object file
src/lib/cat_ae.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ae.o
.PHONY : src/lib/cat_ae.o

# target to preprocess a source file
src/lib/cat_ae.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ae.i
.PHONY : src/lib/cat_ae.i

# target to generate assembly for a file
src/lib/cat_ae.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ae.s
.PHONY : src/lib/cat_ae.s

# target to build an object file
src/lib/cat_anet.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_anet.o
.PHONY : src/lib/cat_anet.o

# target to preprocess a source file
src/lib/cat_anet.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_anet.i
.PHONY : src/lib/cat_anet.i

# target to generate assembly for a file
src/lib/cat_anet.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_anet.s
.PHONY : src/lib/cat_anet.s

# target to build an object file
src/lib/cat_ccmap.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ccmap.o
.PHONY : src/lib/cat_ccmap.o

# target to preprocess a source file
src/lib/cat_ccmap.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ccmap.i
.PHONY : src/lib/cat_ccmap.i

# target to generate assembly for a file
src/lib/cat_ccmap.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ccmap.s
.PHONY : src/lib/cat_ccmap.s

# target to build an object file
src/lib/cat_clog.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_clog.o
.PHONY : src/lib/cat_clog.o

# target to preprocess a source file
src/lib/cat_clog.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_clog.i
.PHONY : src/lib/cat_clog.i

# target to generate assembly for a file
src/lib/cat_clog.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_clog.s
.PHONY : src/lib/cat_clog.s

# target to build an object file
src/lib/cat_dict.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_dict.o
.PHONY : src/lib/cat_dict.o

# target to preprocess a source file
src/lib/cat_dict.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_dict.i
.PHONY : src/lib/cat_dict.i

# target to generate assembly for a file
src/lib/cat_dict.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_dict.s
.PHONY : src/lib/cat_dict.s

# target to build an object file
src/lib/cat_ezxml.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ezxml.o
.PHONY : src/lib/cat_ezxml.o

# target to preprocess a source file
src/lib/cat_ezxml.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ezxml.i
.PHONY : src/lib/cat_ezxml.i

# target to generate assembly for a file
src/lib/cat_ezxml.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_ezxml.s
.PHONY : src/lib/cat_ezxml.s

# target to build an object file
src/lib/cat_json.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_json.o
.PHONY : src/lib/cat_json.o

# target to preprocess a source file
src/lib/cat_json.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_json.i
.PHONY : src/lib/cat_json.i

# target to generate assembly for a file
src/lib/cat_json.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_json.s
.PHONY : src/lib/cat_json.s

# target to build an object file
src/lib/cat_mpsc_queue.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_mpsc_queue.o
.PHONY : src/lib/cat_mpsc_queue.o

# target to preprocess a source file
src/lib/cat_mpsc_queue.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_mpsc_queue.i
.PHONY : src/lib/cat_mpsc_queue.i

# target to generate assembly for a file
src/lib/cat_mpsc_queue.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_mpsc_queue.s
.PHONY : src/lib/cat_mpsc_queue.s

# target to build an object file
src/lib/cat_network_util.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_network_util.o
.PHONY : src/lib/cat_network_util.o

# target to preprocess a source file
src/lib/cat_network_util.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_network_util.i
.PHONY : src/lib/cat_network_util.i

# target to generate assembly for a file
src/lib/cat_network_util.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_network_util.s
.PHONY : src/lib/cat_network_util.s

# target to build an object file
src/lib/cat_sds.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_sds.o
.PHONY : src/lib/cat_sds.o

# target to preprocess a source file
src/lib/cat_sds.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_sds.i
.PHONY : src/lib/cat_sds.i

# target to generate assembly for a file
src/lib/cat_sds.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_sds.s
.PHONY : src/lib/cat_sds.s

# target to build an object file
src/lib/cat_stack.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_stack.o
.PHONY : src/lib/cat_stack.o

# target to preprocess a source file
src/lib/cat_stack.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_stack.i
.PHONY : src/lib/cat_stack.i

# target to generate assembly for a file
src/lib/cat_stack.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_stack.s
.PHONY : src/lib/cat_stack.s

# target to build an object file
src/lib/cat_static_queue.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_static_queue.o
.PHONY : src/lib/cat_static_queue.o

# target to preprocess a source file
src/lib/cat_static_queue.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_static_queue.i
.PHONY : src/lib/cat_static_queue.i

# target to generate assembly for a file
src/lib/cat_static_queue.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_static_queue.s
.PHONY : src/lib/cat_static_queue.s

# target to build an object file
src/lib/cat_time_util.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_time_util.o
.PHONY : src/lib/cat_time_util.o

# target to preprocess a source file
src/lib/cat_time_util.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_time_util.i
.PHONY : src/lib/cat_time_util.i

# target to generate assembly for a file
src/lib/cat_time_util.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/src/lib/cat_time_util.s
.PHONY : src/lib/cat_time_util.s

# target to build an object file
tests/catclient.o:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/tests/catclient.o
.PHONY : tests/catclient.o

# target to preprocess a source file
tests/catclient.i:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/tests/catclient.i
.PHONY : tests/catclient.i

# target to generate assembly for a file
tests/catclient.s:
	$(MAKE) -f CMakeFiles/catclient.dir/build.make CMakeFiles/catclient.dir/tests/catclient.s
.PHONY : tests/catclient.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... catclient"
	@echo "... edit_cache"
	@echo "... src/ccat/client.o"
	@echo "... src/ccat/client.i"
	@echo "... src/ccat/client.s"
	@echo "... src/ccat/client_config.o"
	@echo "... src/ccat/client_config.i"
	@echo "... src/ccat/client_config.s"
	@echo "... src/ccat/context.o"
	@echo "... src/ccat/context.i"
	@echo "... src/ccat/context.s"
	@echo "... src/ccat/encoder.o"
	@echo "... src/ccat/encoder.i"
	@echo "... src/ccat/encoder.s"
	@echo "... src/ccat/encoder_binary.o"
	@echo "... src/ccat/encoder_binary.i"
	@echo "... src/ccat/encoder_binary.s"
	@echo "... src/ccat/encoder_text.o"
	@echo "... src/ccat/encoder_text.i"
	@echo "... src/ccat/encoder_text.s"
	@echo "... src/ccat/functions.o"
	@echo "... src/ccat/functions.i"
	@echo "... src/ccat/functions.s"
	@echo "... src/ccat/message.o"
	@echo "... src/ccat/message.i"
	@echo "... src/ccat/message.s"
	@echo "... src/ccat/message_aggregator.o"
	@echo "... src/ccat/message_aggregator.i"
	@echo "... src/ccat/message_aggregator.s"
	@echo "... src/ccat/message_aggregator_event.o"
	@echo "... src/ccat/message_aggregator_event.i"
	@echo "... src/ccat/message_aggregator_event.s"
	@echo "... src/ccat/message_aggregator_metric.o"
	@echo "... src/ccat/message_aggregator_metric.i"
	@echo "... src/ccat/message_aggregator_metric.s"
	@echo "... src/ccat/message_aggregator_trans.o"
	@echo "... src/ccat/message_aggregator_trans.i"
	@echo "... src/ccat/message_aggregator_trans.s"
	@echo "... src/ccat/message_helper.o"
	@echo "... src/ccat/message_helper.i"
	@echo "... src/ccat/message_helper.s"
	@echo "... src/ccat/message_id.o"
	@echo "... src/ccat/message_id.i"
	@echo "... src/ccat/message_id.s"
	@echo "... src/ccat/message_manager.o"
	@echo "... src/ccat/message_manager.i"
	@echo "... src/ccat/message_manager.s"
	@echo "... src/ccat/message_sender.o"
	@echo "... src/ccat/message_sender.i"
	@echo "... src/ccat/message_sender.s"
	@echo "... src/ccat/message_tree.o"
	@echo "... src/ccat/message_tree.i"
	@echo "... src/ccat/message_tree.s"
	@echo "... src/ccat/monitor.o"
	@echo "... src/ccat/monitor.i"
	@echo "... src/ccat/monitor.s"
	@echo "... src/ccat/monitor_collector.o"
	@echo "... src/ccat/monitor_collector.i"
	@echo "... src/ccat/monitor_collector.s"
	@echo "... src/ccat/router_json_parser.o"
	@echo "... src/ccat/router_json_parser.i"
	@echo "... src/ccat/router_json_parser.s"
	@echo "... src/ccat/server_connection_manager.o"
	@echo "... src/ccat/server_connection_manager.i"
	@echo "... src/ccat/server_connection_manager.s"
	@echo "... src/ccat/transaction.o"
	@echo "... src/ccat/transaction.i"
	@echo "... src/ccat/transaction.s"
	@echo "... src/cppcat/client.o"
	@echo "... src/cppcat/client.i"
	@echo "... src/cppcat/client.s"
	@echo "... src/cppcat/event.o"
	@echo "... src/cppcat/event.i"
	@echo "... src/cppcat/event.s"
	@echo "... src/cppcat/metric.o"
	@echo "... src/cppcat/metric.i"
	@echo "... src/cppcat/metric.s"
	@echo "... src/cppcat/transaction.o"
	@echo "... src/cppcat/transaction.i"
	@echo "... src/cppcat/transaction.s"
	@echo "... src/lib/cat_ae.o"
	@echo "... src/lib/cat_ae.i"
	@echo "... src/lib/cat_ae.s"
	@echo "... src/lib/cat_anet.o"
	@echo "... src/lib/cat_anet.i"
	@echo "... src/lib/cat_anet.s"
	@echo "... src/lib/cat_ccmap.o"
	@echo "... src/lib/cat_ccmap.i"
	@echo "... src/lib/cat_ccmap.s"
	@echo "... src/lib/cat_clog.o"
	@echo "... src/lib/cat_clog.i"
	@echo "... src/lib/cat_clog.s"
	@echo "... src/lib/cat_dict.o"
	@echo "... src/lib/cat_dict.i"
	@echo "... src/lib/cat_dict.s"
	@echo "... src/lib/cat_ezxml.o"
	@echo "... src/lib/cat_ezxml.i"
	@echo "... src/lib/cat_ezxml.s"
	@echo "... src/lib/cat_json.o"
	@echo "... src/lib/cat_json.i"
	@echo "... src/lib/cat_json.s"
	@echo "... src/lib/cat_mpsc_queue.o"
	@echo "... src/lib/cat_mpsc_queue.i"
	@echo "... src/lib/cat_mpsc_queue.s"
	@echo "... src/lib/cat_network_util.o"
	@echo "... src/lib/cat_network_util.i"
	@echo "... src/lib/cat_network_util.s"
	@echo "... src/lib/cat_sds.o"
	@echo "... src/lib/cat_sds.i"
	@echo "... src/lib/cat_sds.s"
	@echo "... src/lib/cat_stack.o"
	@echo "... src/lib/cat_stack.i"
	@echo "... src/lib/cat_stack.s"
	@echo "... src/lib/cat_static_queue.o"
	@echo "... src/lib/cat_static_queue.i"
	@echo "... src/lib/cat_static_queue.s"
	@echo "... src/lib/cat_time_util.o"
	@echo "... src/lib/cat_time_util.i"
	@echo "... src/lib/cat_time_util.s"
	@echo "... tests/catclient.o"
	@echo "... tests/catclient.i"
	@echo "... tests/catclient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

